import { test, expect } from '@playwright/test';
import { createHmac } from 'node:crypto';
import ExcelJS from 'exceljs';
import { readFile } from 'node:fs/promises';

const fixture = 'http://127.0.0.1:4323';
test('admin workflow, conflict/failure recovery, export and access control', async ({ page, context, request }) => {
  test.setTimeout(240_000);
  await request.post(`${fixture}/__test/reset`);
  const payload = `admin.${Date.now() + 3_600_000}`;
  const value = `${payload}.${createHmac('sha256', 'fee-test-secret').update(payload).digest('base64url')}`;
  await context.addCookies([{ name: 'admin_session', value, domain: '127.0.0.1', path: '/', httpOnly: true }]);
  await page.goto('/admin/non-covered');
  await expect(page.getByRole('heading', { name: '비급여 관리', exact: true })).toBeVisible();
  await expect(page.locator('[data-fee-id]')).toHaveCount(173);
  await page.screenshot({ path: '/tmp/ys-fee-admin-desktop.png', fullPage: false });
  const stale = await context.newPage(); await stale.goto('/admin/non-covered');

  await page.getByRole('button', { name: '항목 추가', exact: true }).click();
  let dialog = page.getByRole('dialog');
  await dialog.getByLabel('명칭', { exact: false }).fill('관리 검증 항목');
  await dialog.getByLabel('코드', { exact: true }).fill('00123');
  await dialog.getByLabel('비용', { exact: true }).fill('0');
  await dialog.getByLabel('최저비용', { exact: true }).fill('200');
  await dialog.getByLabel('최고비용', { exact: true }).fill('100');
  await dialog.getByRole('button', { name: '변경 내용 확인', exact: true }).click();
  await expect(dialog.getByRole('alert')).toContainText('최저비용');
  await dialog.getByLabel('최저비용', { exact: true }).fill('');
  await dialog.getByLabel('최고비용', { exact: true }).fill('');
  await dialog.getByRole('button', { name: '변경 내용 확인', exact: true }).click();
  await expect(dialog).toContainText('0원');
  await request.post(`${fixture}/__test/fail`);
  await dialog.getByRole('button', { name: '저장하고 홈페이지 반영' }).click();
  await expect(dialog.getByRole('alert')).toContainText('저장하지 못했습니다');
  await expect(dialog).toContainText('관리 검증 항목');
  await dialog.getByRole('button', { name: '저장하고 홈페이지 반영' }).click();
  await expect(page.getByRole('status')).toContainText('홈페이지에 반영');
  let state = await (await request.get(`${fixture}/__test/state`)).json();
  const id = state.snapshot.content.items.find((i: { name: string }) => i.name === '관리 검증 항목').id;
  await expect(page.locator(`[data-fee-id="${id}"]`)).toContainText('0원');

  const publicPage = await context.newPage(); await publicPage.goto('/non-covered');
  await expect(publicPage.locator('tbody tr').filter({ hasText: '관리 검증 항목' })).toContainText('00123');
  await page.getByLabel('항목명·코드 검색').fill('00123');
  await expect(page.locator('[data-fee-id]')).toHaveCount(1);
  await page.locator(`[data-fee-id="${id}"]`).getByRole('button', { name: '수정', exact: true }).click();
  dialog = page.getByRole('dialog'); await dialog.getByLabel('비용', { exact: true }).fill('12000');
  await dialog.getByRole('button', { name: '변경 내용 확인', exact: true }).click();
  await dialog.getByRole('button', { name: '저장하고 홈페이지 반영' }).click();
  await expect(page.locator(`[data-fee-id="${id}"]`)).toContainText('12,000원');

  await stale.locator('[data-fee-id]').first().getByRole('button', { name: '수정', exact: true }).click();
  await stale.getByRole('dialog').getByLabel('비용', { exact: true }).fill('160000');
  await stale.getByRole('button', { name: '변경 내용 확인', exact: true }).click();
  await stale.getByRole('button', { name: '저장하고 홈페이지 반영' }).click();
  await expect(stale.getByRole('dialog').getByRole('alert')).toContainText('다른 변경이 먼저 저장');
  await stale.close();

  await page.locator(`[data-fee-id="${id}"]`).getByRole('button', { name: '삭제', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: '취소', exact: true }).click();
  await expect(page.locator(`[data-fee-id="${id}"]`)).toHaveCount(1);
  await page.locator(`[data-fee-id="${id}"]`).getByRole('button', { name: '삭제', exact: true }).click();
  await page.getByRole('button', { name: '확인하고 반영' }).click();
  await expect(page.locator(`[data-fee-id="${id}"]`)).toHaveCount(0);
  await publicPage.reload(); await expect(publicPage.locator('tbody tr').filter({ hasText: '관리 검증 항목' })).toHaveCount(0);
  const [download] = await Promise.all([page.waitForEvent('download'), page.getByRole('button', { name: '엑셀 다운로드', exact: true }).click()]);
  const path = await download.path(); const workbook = new ExcelJS.Workbook(); await workbook.xlsx.load(await readFile(path!) as never);
  expect(workbook.getWorksheet('비급여 안내')!.rowCount).toBe(176);
  expect(workbook.getWorksheet('변경 내역')!.rowCount).toBe(4);
  await page.getByLabel('공개 상태').selectOption('deleted');
  await page.locator(`[data-fee-id="${id}"]`).getByRole('button', { name: '복원', exact: true }).click();
  await page.getByRole('button', { name: '확인하고 반영' }).click();
  await page.getByLabel('공개 상태').selectOption('active');
  await expect(page.locator(`[data-fee-id="${id}"]`)).toContainText('12,000원');

  await page.getByRole('button', { name: '분류·순서 관리', exact: true }).click();
  await page.getByLabel('새 대분류 이름', { exact: true }).fill('관리 검증 대분류');
  await page.getByRole('button', { name: '대분류 추가', exact: true }).click();
  await page.getByRole('button', { name: '확인하고 반영' }).click();
  const section = page.locator('section').filter({ has: page.locator('input[value="관리 검증 대분류"]') });
  await section.getByLabel('새 분류 이름', { exact: true }).fill('관리 검증 분류');
  await section.getByRole('button', { name: '분류 추가', exact: true }).click();
  await page.getByRole('button', { name: '확인하고 반영' }).click();
  await expect(section.getByLabel('분류 이름', { exact: true })).toHaveValue('관리 검증 분류');
  await page.getByRole('button', { name: '변경 이력', exact: true }).click();
  await expect(page.locator('details')).toHaveCount(6);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: '항목 관리', exact: true }).click();
  await page.getByRole('button', { name: '항목 추가', exact: true }).click();
  await expect(page.getByRole('dialog').getByLabel('명칭', { exact: false })).toBeVisible();
  await page.screenshot({ path: '/tmp/ys-fee-admin-mobile.png', fullPage: false });
  await page.getByRole('button', { name: '닫기', exact: true }).click();
  await context.clearCookies();
  await page.goto('/admin/non-covered'); await expect(page).toHaveURL(/\/admin\/login/);
  const denied = await request.get('/api/admin/non-covered/export'); expect(denied.status()).toBe(401);
  state = await (await request.get(`${fixture}/__test/state`)).json(); expect(state.snapshot.version).toBe(7);
});
